/**
 * PRD §7.3 step 4, and §6.2: the replay is "generated by default, offered
 * before the still". The order of this sheet is the argument — if the effort
 * signal is what makes a piece worth posting, it cannot be the third option
 * behind two JPEGs.
 */
import { MAX_LAYERS } from '@collage/shared/constants';
import { store } from '../state/store.ts';
import { el, clear } from './dom.ts';
import { exportPiece } from '../export/piece.ts';
import { exportStory } from '../export/story.ts';
import { exportReplay, replaySupported, type ReplayResult } from '../export/replay.ts';
import { mintVersion, pushRender, type Published } from '../export/publish.ts';
import { track } from '../lib/metrics.ts';

export class ExportSheet {
  readonly el: HTMLElement;
  private body: HTMLElement;
  private open = false;
  private published: Published | null = null;
  private piece: { blob: Blob; canvas: HTMLCanvasElement } | null = null;
  private story: { blob: Blob; canvas: HTMLCanvasElement } | null = null;
  private replay: ReplayResult | null = null;
  private busy = false;

  constructor() {
    this.body = el('div', { class: 'sheet-body' });
    this.el = el('div', { class: 'sheet', hidden: true, role: 'dialog', 'aria-modal': 'true', 'aria-label': 'Export' }, [
      el('div', { class: 'sheet-panel' }, [
        el('button', { class: 'sheet-close', type: 'button', 'aria-label': 'Close', text: '✕', onclick: () => this.close() }),
        this.body,
      ]),
    ]);
    this.el.addEventListener('click', (e) => { if (e.target === this.el) this.close(); });
  }

  async show(): Promise<void> {
    if (this.open) return;
    this.open = true;
    this.el.hidden = false;
    this.render();
    track('export', { stage: 'opened', layers: store.comp.layers.length });

    // The URL exists before any share action.
    if (!this.published) {
      try {
        this.published = await mintVersion();
        this.render();
      } catch (err) {
        console.warn('mint failed', err);
        this.render();
      }
    }
    await this.buildReplay();
  }

  close(): void {
    this.open = false;
    this.el.hidden = true;
  }

  private async buildReplay(): Promise<void> {
    if (this.replay || this.busy) return;
    if (!replaySupported()) { this.render(); return; }
    this.busy = true;
    this.render();
    try {
      this.replay = await exportReplay(store.comp, () => {});
      if (this.published) await pushRender(this.published.id, 'replay', this.replay.blob).catch(() => {});
    } catch (err) {
      console.warn('replay failed', err);
    } finally {
      this.busy = false;
      this.render();
    }
  }

  private async ensureStills(): Promise<void> {
    if (!this.piece) {
      this.piece = await exportPiece(store.comp);
      if (this.published) await pushRender(this.published.id, 'piece', this.piece.blob).catch(() => {});
    }
    if (!this.story) {
      this.story = await exportStory(store.comp, this.piece.canvas);
      if (this.published) await pushRender(this.published.id, 'story', this.story.blob).catch(() => {});
    }
  }

  private render(): void {
    clear(this.body);
    const layers = store.comp.layers.length;

    this.body.append(el('h2', { class: 'sheet-title', text: layers ? 'Your piece' : 'Nothing on the canvas yet' }));
    if (!layers) {
      this.body.append(el('p', { class: 'hint', text: 'Place something from the tray first.' }));
      return;
    }

    // The replay leads.
    this.body.append(el('section', { class: 'export-row' }, [
      el('h3', { text: 'The build' }),
      this.replay
        ? (() => {
            const v = el('video', { class: 'replay-video', autoplay: true, loop: true, muted: true, playsinline: true, controls: true });
            v.src = URL.createObjectURL(this.replay!.blob);
            return v;
          })()
        : el('div', { class: 'replay-placeholder' }, [
            el('p', { text: this.busy ? 'Rendering the build…' : replaySupported() ? 'Preparing…' : 'This browser cannot record video — the stills still work.' }),
          ]),
      el('p', { class: 'hint', text: 'Layer by layer, the way you made it.' }),
      this.replay ? this.shareRow('replay') : null,
    ]));

    this.body.append(el('section', { class: 'export-row' }, [
      el('h3', { text: 'The still' }),
      el('div', { class: 'row' }, [
        el('button', { class: 'pill', type: 'button', text: 'Save 4:5', onclick: () => this.saveStill('piece') }),
        el('button', { class: 'pill', type: 'button', text: 'Save 9:16 story', onclick: () => this.saveStill('story') }),
      ]),
      this.shareRow('piece'),
    ]));

    this.body.append(el('section', { class: 'export-row' }, [
      el('h3', { text: 'The link' }),
      this.published
        ? el('div', { class: 'row' }, [
            el('input', { class: 'link-input', readonly: true, value: this.published.url, onclick: (e: Event) => (e.target as HTMLInputElement).select() }),
            el('button', {
              class: 'pill', type: 'button', text: 'Copy',
              onclick: async () => {
                await navigator.clipboard.writeText(this.published!.url).catch(() => {});
                track('share', { channel: 'copy_link', included_replay: false });
              },
            }),
          ])
        : el('p', { class: 'hint', text: 'Minting a permanent link…' }),
      el('p', { class: 'hint', text: 'Opens as a piece someone can change, not a flat image.' }),
    ]));

    if (layers >= MAX_LAYERS) {
      this.body.append(el('p', { class: 'hint', text: `${MAX_LAYERS} pieces is the limit — that is the format, not a bug.` }));
    }
  }

  private shareRow(kind: 'piece' | 'replay'): HTMLElement {
    return el('div', { class: 'row' }, [
      el('button', {
        class: 'pill pill-primary',
        type: 'button',
        text: kind === 'replay' ? 'Share the build' : 'Share',
        onclick: () => this.share(kind),
      }),
    ]);
  }

  private async saveStill(kind: 'piece' | 'story'): Promise<void> {
    await this.ensureStills();
    const item = kind === 'piece' ? this.piece! : this.story!;
    download(item.blob, `collage-${this.published?.id ?? 'piece'}-${kind}.jpg`);
    track('export', { kind, action: 'save' });
  }

  private async share(kind: 'piece' | 'replay'): Promise<void> {
    const url = this.published?.url ?? location.href;
    let file: File | undefined;
    if (kind === 'replay' && this.replay) {
      file = new File([this.replay.blob], `collage.${this.replay.extension}`, { type: this.replay.blob.type });
    } else {
      await this.ensureStills();
      file = new File([this.piece!.blob], 'collage.jpg', { type: 'image/jpeg' });
    }

    const data: ShareData = { url, text: 'Made this.' };
    if (file && navigator.canShare?.({ files: [file] })) data.files = [file];

    // Metric 3 (PRD §11) — of shares, what fraction include the replay.
    const includedReplay = kind === 'replay';
    try {
      if (navigator.share) {
        await navigator.share(data);
        track('share', { channel: 'native', included_replay: includedReplay }, this.published?.id);
        if (includedReplay) track('share_included_replay', {}, this.published?.id);
        return;
      }
    } catch (err) {
      if ((err as Error).name === 'AbortError') return;
    }
    if (file) download(file, file.name);
    await navigator.clipboard.writeText(url).catch(() => {});
    track('share', { channel: 'fallback', included_replay: includedReplay }, this.published?.id);
    if (includedReplay) track('share_included_replay', {}, this.published?.id);
  }
}

function download(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
