/**
 * PRD §6.2 — "The replay is a feature, not an export option."
 *
 * It is the effort signal: if AI removes the visible labour, the labour has to
 * be reconstructed somewhere, and this is where. It is generated by default
 * and offered before the still, and it is built from the layer order and
 * timings the version record already keeps — no separate capture, no separate
 * source of truth.
 *
 * Rendered client-side (PRD §10, Performance), by driving the same renderer
 * frame by frame into a MediaRecorder.
 */
import { PIECE, REPLAY, STORY } from '@collage/shared/constants';
import { orderedLayers, type Composition } from '@collage/shared/version';
import { renderComposition } from '../render/renderer.ts';
import { paletteRamp } from '../state/store.ts';
import { fragmentStore } from '../render/fragmentStore.ts';
import { exportCanvas } from './render.ts';
import { outpaintTo } from './story.ts';

const CANDIDATE_TYPES = [
  'video/mp4;codecs=avc1.42E01E',
  'video/mp4',
  'video/webm;codecs=vp9',
  'video/webm;codecs=vp8',
  'video/webm',
];

export function replaySupported(): boolean {
  return typeof MediaRecorder !== 'undefined' && CANDIDATE_TYPES.some((t) => MediaRecorder.isTypeSupported(t));
}

function pickType(): string | undefined {
  return CANDIDATE_TYPES.find((t) => MediaRecorder.isTypeSupported(t));
}

/** 4–8s, scaled to how much there is to watch (PRD §6.1). */
export function replayDurationMs(layerCount: number): number {
  return Math.min(REPLAY.maxMs, Math.max(REPLAY.minMs, 1600 + layerCount * 430));
}

export interface ReplayResult {
  blob: Blob;
  mimeType: string;
  extension: 'mp4' | 'webm';
  durationMs: number;
}

export async function exportReplay(
  comp: Composition,
  onProgress?: (fraction: number) => void,
): Promise<ReplayResult> {
  const type = pickType();
  if (!type) throw new Error('This browser cannot record the replay.');

  const layers = orderedLayers(comp);
  const buildMs = replayDurationMs(layers.length);
  const totalMs = buildMs + REPLAY.outroMs;

  // Composed at piece size, then framed 9:16 through the same outpaint the
  // story export uses, so the two reads as one artifact.
  const piece = exportCanvas(PIECE.w, PIECE.h);
  const pieceCtx = piece.getContext('2d')!;
  const stage = exportCanvas(STORY.w, STORY.h);
  const stageCtx = stage.getContext('2d')!;

  // Warm every raster before recording; a pipeline run mid-capture would show
  // up as a stall in the video.
  await warm(comp, pieceCtx);

  const ramp = paletteRamp(comp.palette);
  const stream = stage.captureStream(REPLAY.fps);
  const chunks: BlobPart[] = [];
  const recorder = new MediaRecorder(stream, { mimeType: type, videoBitsPerSecond: 6_000_000 });
  recorder.ondataavailable = (e) => { if (e.data.size) chunks.push(e.data); };

  const done = new Promise<void>((resolve) => { recorder.onstop = () => resolve(); });
  recorder.start();

  const started = performance.now();
  await new Promise<void>((resolve) => {
    const frame = (): void => {
      const elapsed = performance.now() - started;
      const t = Math.min(1, elapsed / buildMs);
      // Ease the build so the last fragments do not race past.
      const eased = t * t * (3 - 2 * t);
      const exact = eased * layers.length;
      const count = Math.floor(exact);

      renderComposition(pieceCtx, comp, {
        width: PIECE.w,
        height: PIECE.h,
        paletteRamp: ramp,
        reveal: { count, progress: exact - count },
        finalOnly: true,
      });

      const framed = outpaintTo(piece, STORY.w, STORY.h, comp.substrate);
      stageCtx.drawImage(framed, 0, 0);

      if (elapsed > buildMs) drawMark(stageCtx, Math.min(1, (elapsed - buildMs) / 500));
      onProgress?.(Math.min(1, elapsed / totalMs));

      if (elapsed >= totalMs) { resolve(); return; }
      requestAnimationFrame(frame);
    };
    requestAnimationFrame(frame);
  });

  recorder.stop();
  await done;
  stream.getTracks().forEach((t) => t.stop());

  const mime = recorder.mimeType || type;
  return {
    blob: new Blob(chunks, { type: mime }),
    mimeType: mime,
    extension: mime.includes('mp4') ? 'mp4' : 'webm',
    durationMs: totalMs,
  };
}

/** PRD §6.3 — "No watermark on the still. Small mark on the replay's final
 *  frame only." */
function drawMark(ctx: CanvasRenderingContext2D, fade: number): void {
  ctx.save();
  ctx.globalAlpha = Math.min(0.72, fade);
  ctx.font = '500 30px Georgia, "Times New Roman", serif';
  ctx.textAlign = 'center';
  ctx.fillStyle = 'rgba(255,252,244,0.95)';
  ctx.shadowColor = 'rgba(0,0,0,0.6)';
  ctx.shadowBlur = 14;
  ctx.fillText('made on collage', STORY.w / 2, STORY.h - 96);
  ctx.restore();
}

async function warm(comp: Composition, ctx: CanvasRenderingContext2D): Promise<void> {
  const deadline = Date.now() + 12000;
  const ramp = paletteRamp(comp.palette);
  renderComposition(ctx, comp, { width: PIECE.w, height: PIECE.h, paletteRamp: ramp });
  while (!fragmentStore.isSettled() && Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 40));
    renderComposition(ctx, comp, { width: PIECE.w, height: PIECE.h, paletteRamp: ramp });
  }
}
